services:
  auth-server:
    build:
      context: ./FAH-auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JWT_ACCESS_SECRET=your-super-secret-access-key-min-32-chars
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-min-32-chars
    depends_on:
      auth-db:
        condition: service_healthy
  fah_frontend:
    build: 
      context: ./fah-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      - auth-server
    
    environment:
      NEXT_PUBLIC_BASE_API: 0.0.0.0:8081
 
  auth-db:
    container_name: auth_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: actual_database_password_here
      PGDATA: /data/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  db-data:
