networks:
  fah:
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - profile-service
      - fah_frontend
      - parsing_service

    networks:
      - fah

  fah_frontend:
    build: 
      context: ./fah-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      - profile-service
      - parsing_service
    
    env_file:
      - .env
    networks:
      - fah
  parsing_service:
    build:
      context: ./FAH_parsing_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - fah
  db:
    image: postgres:17
    container_name: db
    env_file:
      - ./profileService/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fah_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - fah

  profile-service:
    build:
      context: ./profileService
      dockerfile: Dockerfile
    container_name: profile-service
    ports:
      - "8083:8083"
    depends_on:
      - db
      - parsing_service
    env_file:
      - ./profileService/.env
    networks:
      - fah
volumes:
  postgres_data:
