// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jackc/pgx/v5/pgxpool"
	allocationHandler "gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/handler/allocation"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/handler/courses"
	facultyProfile2 "gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/handler/facultyProfile"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/handler/filters"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/handler/parse"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/academicYear"
	allocationService "gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/allocation"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/completeCourse"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/completeUser"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/course"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/courseInstance"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/facultyProfile"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/institute"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/language"
	Parsing "gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/parsing"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/position"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/profileCourseInstance"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/profileInstitute"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/profileLanguage"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/profileVersion"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/program"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/programCourseInstance"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/responsibleInstitute"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/semester"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/staff"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/track"
	trackcourseinstance "gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/trackCourseInstance"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/service/workload"
	"gitlab.pg.innopolis.university/f.markin/fah/profileService/internal/storage/postgres"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeApp(pool *pgxpool.Pool, logger *zap.Logger) (*App, error) {
	facultyProfileRepo := postgres.NewFacultyProfileRepo(pool, logger)
	service := facultyProfile.NewService(facultyProfileRepo, logger)
	userInstituteRepo := postgres.NewUserInstituteRepo(pool, logger)
	profileInstituteService := profileInstitute.NewService(userInstituteRepo, logger)
	userLanguageRepo := postgres.NewUserLanguageRepo(pool, logger)
	profileLanguageService := profileLanguage.NewService(userLanguageRepo, logger)
	profileCourseInstanceRepo := postgres.NewUserCourseInstance(pool, logger)
	profileCourseInstanceService := profileCourseInstance.NewService(profileCourseInstanceRepo, logger)
	positionRepo := postgres.NewPositionRepo(pool, logger)
	positionService := position.NewService(positionRepo, logger)
	instituteRepo := postgres.NewInstituteRepo(pool, logger)
	instituteService := institute.NewService(instituteRepo, logger)
	profileVersionRepo := postgres.NewUserProfileVersionRepo(pool, logger)
	profileVersionService := profileVersion.NewService(pool, profileVersionRepo, logger)
	workloadRepo := postgres.NewSemesterWorkloadRepo(pool, logger)
	workloadService := workload.NewService(pool, workloadRepo, logger)
	handler := facultyProfile2.NewHandler(service, profileInstituteService, profileLanguageService, profileCourseInstanceService, positionService, instituteService, profileVersionService, workloadService, logger)
	courseInstanceRepo := postgres.NewCourseInstanceRepo(pool, logger)
	courseInstanceService := courseInstance.NewService(pool, courseInstanceRepo, logger)
	courseRepo := postgres.NewCourseRepo(pool, logger)
	courseService := course.NewService(courseRepo, logger)
	trackRepo := postgres.NewTrackRepo(pool, logger)
	trackCourseRepo := postgres.NewTrackCourseRepo(pool, logger)
	trackService := track.NewService(trackRepo, trackCourseRepo, logger)
	programRepo := postgres.NewProgramRepo(pool, logger)
	programCourseRepo := postgres.NewProgramCourseRepo(pool, logger)
	programService := program.NewService(programRepo, programCourseRepo, logger)
	trackcourseinstanceService := trackcourseinstance.NewService(trackCourseRepo, logger)
	programCourseInstanceService := programCourseInstance.NewService(programCourseRepo, logger)
	completeCourseService := completeCourse.NewService(courseInstanceService, courseService, trackService, programService, trackcourseinstanceService, programCourseInstanceService, logger)
	staffRepo := postgres.NewStaffRepo(pool, logger)
	staffService := staff.NewStaffService(pool, staffRepo, logger)
	academicYearRepo := postgres.NewAcademicYearRepo(pool, logger)
	academicYearService := academicYear.NewService(academicYearRepo, logger)
	semesterRepo := postgres.NewSemesterRepo(pool, logger)
	semesterService := semester.NewService(semesterRepo, logger)
	responsibleInstituteRepo := postgres.NewResponsibleInstituteRepo(pool, logger)
	responsibleInstituteService := responsibleInstitute.NewService(responsibleInstituteRepo, logger)
	coursesHandler := courses.NewHandler(completeCourseService, staffService, profileInstituteService, academicYearService, semesterService, responsibleInstituteService, profileVersionService, service, courseInstanceService, courseService, programService, trackService, programCourseInstanceService, trackcourseinstanceService, logger)
	filtersHandler := filters.NewHandler(positionService, instituteService, academicYearService, programService, semesterService, responsibleInstituteService, logger)
	languageRepo := postgres.NewLanguageRepo(pool, logger)
	languageService := language.NewService(languageRepo, logger)
	completeUserService := completeUser.NewService(logger, service, profileVersionService, languageService, profileLanguageService, instituteService, profileInstituteService)
	parsingService := Parsing.NewService(logger, completeCourseService, completeUserService, positionService, responsibleInstituteService)
	parseHandler := parse.NewHandler(logger, parsingService)
	allocationServiceService := allocationService.NewService(pool, logger, profileVersionRepo, staffRepo, courseInstanceRepo, workloadRepo)
	allocationHandlerHandler := allocationHandler.NewHandler(allocationServiceService, logger)
	app := NewApp(pool, logger, handler, coursesHandler, filtersHandler, parseHandler, allocationHandlerHandler)
	return app, nil
}
